### ISSUE TITLE
silentfrompdbs

### ISSUE THREAD

**Issue by DNARNAi** [bcov77/silent_tools#4]
I want to inform you that silentfrompdbs script is not working its showing me an error regarding #tem  I have attached an error file please suggest me what i can do ASAP.            
ERROR

silentfrompdbs
silent_tools: Error! Silent file doesn't exist: tmp_biCETbpWEi2yB.silent
silent_tools: Error! Silent file doesn't exist: tmp_biCETbpWEi2yB.silent
rm: cannot remove ‘tmp_biCETbpWEi2yB.silent’: No such file or directory
rm: cannot remove ‘tmp_biCETbpWEi2yB.silent.idx’: No such file or directory
               

Thankyou

**Comment by alllirik** [comment]
Hello! I've encountered the same type of error. Above it there was another error that mentioned the absence of 'H3i.am1bcc.fa.mm.params' file. 

If it's the same thing for you, then look for '-extra_res_fa H3i.am1bcc.fa.mm.params' in the `silentfrompdbs` script and delete it from the corresponding line, as it was suggested in this [issue](https://github.com/bcov77/silent_tools/issues/2)

Hope it helps

**Comment by arikat** [comment]
I'm having the same issue, here is my traceback -- I did delete the extra res parameter and that fixed another issue, but this error comes after deleting that. I have the latest version of pyrosetta and python, no issue there I believe.

**Traceback (most recent call last):**                                                                                                                                                                                                                                                                                      File "/home/user/Software/silent_tools/silentls", line 32, in <module>                                                                                                                                                                                                                      silent_index = silent_tools.get_silent_index( file )                                                                                                                                                                                                                                                                File "/home/user/Software/silent_tools/silent_tools.py", line 35, in get_silent_index                                                                                                                                                                                                       return build_silent_index(file, accept_garbage=accept_garbage)                                                                                                                                                                                                                                                      File "/home/user/Software/silent_tools/silent_tools.py", line 394, in build_silent_index                                                                                                                                                                                                    size = file_size(file)                                                                                                                                                                                                                                                                                              File "/home/user/Software/silent_tools/silent_tools.py", line 433, in file_size                                                                                                                                                                                                             return int(cmd("du -b %s | awk '{print $1}'"%file).strip())                                                                                                                                                                                                                                                       ValueError: invalid literal for int() with base 10: '512178\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)' 

**Traceback (most recent call last):**                                                                                                                                                                                                                                                                                      File "/home/user/Software/silent_tools/silentrename", line 51, in <module>                                                                                                                                                                                                                  silent_index = silent_tools.get_silent_index( silent_file )                                                                                                                                                                                                                                                         File "/home/user/Software/silent_tools/silent_tools.py", line 35, in get_silent_index                                                                                                                                                                                                       return build_silent_index(file, accept_garbage=accept_garbage)                                                                                                                                                                                                                                                      File "/home/user/Software/silent_tools/silent_tools.py", line 394, in build_silent_index                                                                                                                                                                                                    size = file_size(file)                                                                                                                                                                                                                                                                                              File "/home/user/Software/silent_tools/silent_tools.py", line 433, in file_size                                                                                                                                                                                                             return int(cmd("du -b %s | awk '{print $1}'"%file).strip())                                                                                                                                                                                                                                                       ValueError: invalid literal for int() with base 10: '512178\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)'                                                                                                                                                                                     rm: cannot remove 'tmp_K3rnOLHXYPNVa.silent.idx': No such file or directory

**Comment by lindseyguan** [comment]
> I'm having the same issue, here is my traceback -- I did delete the extra res parameter and that fixed another issue, but this error comes after deleting that. I have the latest version of pyrosetta and python, no issue there I believe.
> 
> **Traceback (most recent call last):** File "/home/user/Software/silent_tools/silentls", line 32, in silent_index = silent_tools.get_silent_index( file ) File "/home/user/Software/silent_tools/silent_tools.py", line 35, in get_silent_index return build_silent_index(file, accept_garbage=accept_garbage) File "/home/user/Software/silent_tools/silent_tools.py", line 394, in build_silent_index size = file_size(file) File "/home/user/Software/silent_tools/silent_tools.py", line 433, in file_size return int(cmd("du -b %s | awk '{print $1}'"%file).strip()) ValueError: invalid literal for int() with base 10: '512178\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)'
> 
> **Traceback (most recent call last):** File "/home/user/Software/silent_tools/silentrename", line 51, in silent_index = silent_tools.get_silent_index( silent_file ) File "/home/user/Software/silent_tools/silent_tools.py", line 35, in get_silent_index return build_silent_index(file, accept_garbage=accept_garbage) File "/home/user/Software/silent_tools/silent_tools.py", line 394, in build_silent_index size = file_size(file) File "/home/user/Software/silent_tools/silent_tools.py", line 433, in file_size return int(cmd("du -b %s | awk '{print $1}'"%file).strip()) ValueError: invalid literal for int() with base 10: '512178\n/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)' rm: cannot remove 'tmp_K3rnOLHXYPNVa.silent.idx': No such file or directory

I had this issue as well since the `du` command on my system (macOS) doesn't recognize `-b` as a valid argument. I changed `-b` to `-B 1` on line 394 in silent_tools.py and it fixed it for me.
